name: RushTheFlag
version: 1.1
author: Haxy972
main: fr.haxy972.RushTheFlag.Main
website: https://github.com/Haxy972/RushTheFlag
load: POSTWORLD
commands:
  join:
    description: Choose your team
  kits:
    description: Select your kit
  rushtheflag:
    description: Manage kits, spawns and others...
    aliases: rtf
    permision: RushTheFlag.command
