name: RushTheFlag
version: 1.0
author: Haxy972
main: fr.haxy972.RushTheFlag.Main
website: https://github.com/Haxy972/RushTheFlag
commands:
  join:
    description: Choisir une équipe
  kits:
    description: permet de choisir son kit
  debug:
    description: commande de debug
    permission: admin
  rushtheflag:
    description: Gérer les kits
    aliases: rtf