name: RushTheFlag
version: 1.1
author: Haxy972
main: fr.haxy972.RushTheFlag.Main
website: https://github.com/Haxy972/RushTheFlag
load: POSTWORLD
commands:
  join:
    description: Choisir une équipe
  kits:
    description: permet de choisir son kit
  rushtheflag:
    description: Gérer les kits
    aliases: rtf
    permision: RushTheFlag.allperm
